[package]
name = "onebot_v11_macro"
version = "0.1.0"
edition = "2021"
description = "OneBot v11 macro"
license = "MIT OR Apache-2.0"

[dependencies]
quote = "1.0.35"
syn = "2.0.52"

[lib]
proc-macro = true

